[build]
  command = "gatsby build --log-pages"
  publish = "public/"

[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"