backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: assets
public_folder: /assets

collections:
  # ======================================= <POSTS> =======================================
  - name: news
    label: "News & Announcements"
    folder: content/posts/news
    create: true
    slug: "posts/news/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }
      - name: category
        label: Category
        widget: select
        default: news
        options:
          - { label: News, value: news }
          - { label: Announcement, value: announcement }

  - name: events
    label: "Events"
    folder: content/posts/events
    create: true
    slug: "posts/events/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: awards
    label: "Awards & Honors"
    folder: content/posts/awards
    create: true
    slug: "posts/awards/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: exchange
    label: "Exchange Programs"
    folder: content/posts/exchange
    create: true
    slug: "posts/exchange/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: admissions
    label: "International College Admissions"
    folder: content/posts/admissions
    create: true
    slug: "posts/admissions/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }
      - name: category
        label: Category
        options:
          - { label: "EDI Admissions", value: ed1 }
          - { label: "EDII Admissions", value: ed2 }
          - { label: "EA Admissions", value: ea }
          - { label: "REA Admissions", value: rea }
          - { label: "Non-US Amissions", value: nonus }

  - name: domestic
    label: "Grade 12 Domestic Ranks & College Coordination"
    folder: content/posts/domestic
    create: true
    slug: "posts/domestic/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - {
          name: author,
          label: Author,
          widget: relation,
          collection: people,
          value_field: email,
          search_fields: ["full_name"],
          display_fields: ["{{full_name}} - {{email}}"],
        }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: student_submissions
    label: "Student Submissions"
    folder: content/posts/student-submissions
    create: true
    slug: "posts/student-submissions/{{title}}-{{year}}{{month}}{{day}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}-{{year}}{{month}}{{day}}/index"
    fields:
      - { name: title, label: Title }
      - { name: date, label: "Publish Date", widget: datetime }
      - { name: description, label: Description }
      - { name: author, label: Author }
      - { name: illustration, label: "Illustration", widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list }

  # ======================================= </POSTS> =======================================

  - name: people
    label: People
    folder: content/people
    path: "{{full_name}}-{{email}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    editor:
      preview: false
    fields:
      - { name: full_name, label: "Full Name" }
      - { name: email, label: Email }
      - { name: role, lable: Role }
      - { name: bio, label: Bio }
      - { name: avatar, label: Avatar, widget: image }
